// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nuoauyweckspkqxtlyac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51b2F1eXdlY2tzcGtxeHRseWFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MjU1NTUsImV4cCI6MjA2MzQwMTU1NX0.51_erURkCiR5QasGoiLjcRDnEXohCaOOpN7guFYFx38";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);